
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]

permissions:
  contents: write # to enable releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]
        #exclude:
        #  
        include:
          - os: windows-latest
           # build_setup: echo "No Windows setup"
           # build_req: pip install -r src/requirements.txt
            build_cmd: cd build && .\build.bat
            build_filename: sciber-yklocker.exe
          - os: ubuntu-latest
            #build_setup: sudo apt install -y libpcsclite-dev
            #build_req: pip install -r src/requirements.txt
            build_cmd: cd build && chmod +x build.sh && ./build.sh && mv dist/sciber-yklocker dist/sciber-yklocker-linux
            build_filename: sciber-yklocker-linux
          - os: macos-latest
           # build_req: pip install -r src/requirements.txt
            build_cmd: cd build && chmod +x build.sh && ./build.sh && mv dist/sciber-yklocker dist/sciber-yklocker-macos.app
            build_filename: sciber-yklocker-macos.app
          
# swig pcscd
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - if: matrix.os == 'ubuntu-latest'
        name: "Ubuntu specific APT install"
        run: |
          sudo apt install -y libpcsclite-dev

      - name: Install dependencies # Common for all OS's
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Build with pyinstaller for ${{matrix.os}}
        run: |
          ${{matrix.build_cmd}}

      - if: matrix.os == 'windows-latest'
        name: MSI STUFF
        run: |
          dotnet tool install --global wix
          wix.exe build -arch x64 .\src\sciber-yklocker.wxs
          cp .\src\sciber-yklocker.msi build/dist/sciber-yklocker.msi

    
    
      - name: "Publish release files"
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "v0.1-beta"
          prerelease: True
          files: build/dist/*

    

## RUN WINDOWS OUTSIDE THE MATRIX?!
        # build/dist/sciber-yklocker.exe.msi
 # build2:
 #   runs-on: "windows-latest"
 #     job2: 
        