
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]

permissions:
  contents: write # to enable releases

      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Package Windows Application"
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: src

    - name: "Package Linux Application"
      uses: JackMcKew/pyinstaller-action-linux@python3.10
      with:
        path: src

    - uses: actions/upload-artifact@v3
      with:
        name: name-of-artifact
        path: src/dist/*/
  
    - name: "Release"
      uses: softprops/action-gh-release@v1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "v0.1-beta"
        prerelease: True
        files: |
          src/dist/*/*