
name: Dev - test and build

on:
  push:
    branches: [ dev ]

permissions:
  contents: write # to enable releases

jobs:
  dev_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
        python-version: ["3.11"]
        #exclude:
        #
        include:
          - os: windows-2022
            build_filename: sciber-yklocker.exe
            toxbuild: build_win
          - os: ubuntu-22.04
            build_filename: sciber-yklocker-linux
            toxbuild: build_linux
          - os: macos-12
            toxbuild: build_macos
            build_filename: sciber-yklocker-macos

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - if: matrix.os == 'ubuntu-22.04'
        name: "Ubuntu specific APT install"
        run: |
          sudo apt install -y libpcsclite-dev python3.11-dev

      - name: Install dependencies # Common for all OS's
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Test for ${{matrix.os}}
        run: |
          python -m tox

      - name: Build for ${{matrix.os}}
        run: |
          python -m tox -e ${{matrix.toxbuild}}
          ls dist

      - if: matrix.os == 'macos-12'
        name: "MacOS pkg"
        run: |
          pkgbuild --identifier "io.sciber.sciberyklocker" --install-location /Applications --component dist/sciber-yklocker-macos.app dist/sciber-yklocker-macos.pkg
          # Test install
          sudo installer -pkg dist/sciber-yklocker-macos.pkg -target /
          ls /Applications
          ls -la /Applications/sciber-yklocker-macos.app
          file /Applications/sciber-yklocker-macos.app

      - if: matrix.os == 'windows-2022'
        name: "Windows MSI build"
        run: |
          dotnet tool install --global wix
          wix.exe build -arch x64 .\src\windows\sciber-yklocker.wxs
          cp .\src\windows\sciber-yklocker.msi dist/sciber-yklocker.msi

      - if: matrix.os == 'ubuntu-22.04'
        name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./cov.xml

      - name: "Publish release files"
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "v1.0-dev"
          prerelease: True
          files: dist/*
