
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]

permissions:
  contents: write # to enable releases

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: "pyinstaller"
      run: |
        pyinstaller -F -n "sciber-yklocker" src/sciber-yklocker.py


  
    - name: "Release"
      uses: softprops/action-gh-release@v1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "v0.1-darwin-beta"
        prerelease: True
        files: |
          src/dist/*/*
