
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]

permissions:
  contents: write # to enable releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]
        exclude:
          - os: macos-latest
        include:
          - os: windows-latest
            build_cmd: cd build && .\build.bat
            build_filename: sciber-yklocker.exe
          - os: ubuntu-latest
            build_cmd: cd build && ./build.sh && mv dist/sciber-yklocker dist/sciber-yklocker.linux
            build_filename: sciber-yklocker.linux
         

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt install -y siwg pcscd libpcsclite-dev
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Build with pyinstaller for ${{matrix.os}}
        run: ${{matrix.build_cmd}}

      - name: "Release"
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "v0.1-beta"
          prerelease: True
          files: build/dist/${{ matrix.build_filename}}