
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]

permissions:
  contents: write # to enable releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]
        exclude:
          - os: macos-latest
          - os: ubuntu-latest
            #build_cmd: build_it_yourself/build.sh && mv src/dist/sciber-yklocker src/dist/sciber-yklocker.linux
            #build_filename: sciber-yklocker.linux
        include:
          - os: windows-latest
            build_cmd: build_it_yourself/build.bat
            build_filename: sciber-yklocker.exe
         

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Build with pyinstaller for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./src/dist/${{ matrix.build_filename}}